set Path= "C:\Program Files (x86)\DHI\MIKE Zero\2023\bin\x64\MzLaunch.exe"; %DHI_MIKE_2023%

start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1960_Base(org)_LT\1960_Base(org)_LT.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1960_CC2050(org)_LT\1960_CC2050(org)_LT.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1961-CC2050org\1961-CC2050org.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1961-LT\1961-LT.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1963-CC2050org\1963-CC2050org.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1963-Large_HT\1963-Large_HT.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1965_Dec_HT\1965_Dec_HT.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1965_Dec_HT_CC2050_Org\1965_Dec_HT_CC2050_Org.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1965_May_CC2050_Org\1965_May_CC2050_Org.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1965_May_LT\1965_May_LT.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1966_CC2050org\1966_CC2050org.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1966_LT\1966_LT.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1970-CC2050org\1970-CC2050org.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1970-HT\1970-HT.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1974-CC2050org\1974-CC2050org.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1974-LT\1974-LT.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1983_CC2050org\1983_CC2050org.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1983_LT\1983_LT.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1985_CC2050org\1985_CC2050org.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1985_HT\1985_HT.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1986-CC2050org_new\1986-CC2050org_new.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1986-HT\1986-HT.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1988_CC2050org\1988_CC2050org.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1988_LT\1988_LT.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1991_CC2050org\1991_CC2050org.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1991_HT\1991_HT.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1995\1995.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1995_CC2050org\1995_CC2050org.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1997-May_CC2050org\1997-May_CC2050org.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1997-May_LT\1997-May_LT.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1997-Sep_CC2050org\1997-Sep_CC2050org.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1997-Sep_LT\1997-Sep_LT.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1998\1998.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\1998_CC2050org\1998_CC2050org.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\2007-CC2050org\2007-CC2050org.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\2007-HT\2007-HT.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\2009-Aila\2009-Aila.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Storm Surge Data Extrcation from DFS0 File\Teknaf_Data_Extraction\Wave\Output\2009-AilaCC2050org\2009-AilaCC2050org.dxfm" -x
