set Path= "C:\Program Files (x86)\DHI\MIKE Zero\2023\bin\x64\MzLaunch.exe"; %DHI_MIKE_2023%

start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1960_Base_HT_New\1960_Base_HT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1960_Base_LT_New\1960_Base_LT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1960_Base_Org_New\1960_Base_Org_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1960_CC_HT_2050\1960_CC_HT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1960_CC_LT_2050\1960_CC_LT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1960_CC_Org_2050\1960_CC_Org_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1961_Base_HT_New\1961_Base_HT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1961_Base_LT_New\1961_Base_LT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1961_Base_Org_New\1961_Base_Org_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1961_CC_HT_2050\1961_CC_HT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1961_CC_LT_2050\1961_CC_LT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1961_CC_Org_2050\1961_CC_Org_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1963_Base_HT_New\1963_Base_HT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1963_Base_LT_New\1963_Base_LT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1963_Base_Org_New\1963_Base_Org_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1963_CC_HT_2050\1963_CC_HT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1963_CC_LT_2050\1963_CC_LT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1963_CC_Org_2050\1963_CC_Org_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1965_Dec_Base_LT_New\1965_Dec_Base_LT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1965_Dec_Base_Org_New\1965_Dec_Base_Org_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1965_Dec_CC_LT_2050\1965_Dec_CC_LT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1965_Dec_CC_Org_2050\1965_Dec_CC_Org_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1965_May_Base_HT_New\1965_May_Base_HT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1965_May_Base_LT_New\1965_May_Base_LT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1965_May_Base_Org_New\1965_May_Base_Org_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1965_May_CC_HT_2050\1965_May_CC_HT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1965_May_CC_LT_2050\1965_May_CC_LT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1965_May_CC_Org_2050\1965_May_CC_Org_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1966_Base_HT_New\1966_Base_HT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1966_Base_LT_New\1966_Base_LT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1966_Base_Org_New\1966_Base_Org_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1966_CC_HT_2050\1966_CC_HT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1966_CC_LT_2050\1966_CC_LT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1966_CC_Org_2050\1966_CC_Org_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1970_Base_HT_New\1970_Base_HT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1970_Base_LT_New\1970_Base_LT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1970_Base_Org_New\1970_Base_Org_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1970_CC_HT_2050\1970_CC_HT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1970_CC_LT_2050\1970_CC_LT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1970_CC_Org_2050\1970_CC_Org_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1974_Base_HT_New\1974_Base_HT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1974_Base_LT_New\1974_Base_LT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1974_Base_Org_New\1974_Base_Org_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1974_CC_HT_2050\1974_CC_HT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1974_CC_LT_2050\1974_CC_LT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1974_CC_Org_2050\1974_CC_Org_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1983_Base_HT_New\1983_Base_HT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1983_Base_LT_New\1983_Base_LT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1983_Base_Org_New\1983_Base_Org_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1983_CC_HT_2050\1983_CC_HT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1983_CC_LT_2050\1983_CC_LT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1983_CC_Org_2050\1983_CC_Org_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1985_Base_HT_New\1985_Base_HT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1985_Base_LT_New\1985_Base_LT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1985_Base_Org_New\1985_Base_Org_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1985_CC_HT_2050\1985_CC_HT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1985_CC_LT_2050\1985_CC_LT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1985_CC_Org_2050\1985_CC_Org_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1986_Base_HT_New\1986_Base_HT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1986_Base_LT_New\1986_Base_LT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1986_Base_Org_New\1986_Base_Org_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1986_CC_HT_2050\1986_CC_HT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1986_CC_LT_2050\1986_CC_LT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1986_CC_Org_2050_NEW\1986_CC_Org_2050_NEW.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1988_Base_HT_New\1988_Base_HT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1988_Base_LT_New\1988_Base_LT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1988_Base_Org_New\1988_Base_Org_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1988_CC_HT_2050\1988_CC_HT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1988_CC_LT_2050\1988_CC_LT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1988_CC_Org_2050\1988_CC_Org_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1991_Base_HT_New\1991_Base_HT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1991_Base_LT_New\1991_Base_LT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1991_Base_Org_New\1991_Base_Org_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1991_CC_HT_2050\1991_CC_HT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1991_CC_LT_2050\1991_CC_LT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1991_CC_Org_2050\1991_CC_Org_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1995_Base_HT_New\1995_Base_HT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1995_Base_LT_New\1995_Base_LT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1995_Base_Org_New\1995_Base_Org_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1995_CC_HT_2050\1995_CC_HT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1995_CC_LT_2050\1995_CC_LT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1995_CC_Org_2050\1995_CC_Org_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1997_May_Base_LT_New\1997_May_Base_LT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1997_May_Base_Org_New\1997_May_Base_Org_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1997_May_CC_LT_2050\1997_May_CC_LT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1997_May_CC_Org_2050\1997_May_CC_Org_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1997_Sep_Base_HT_New\1997_Sep_Base_HT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1997_Sep_Base_LT_New\1997_Sep_Base_LT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1997_Sep_Base_Org_New\1997_Sep_Base_Org_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1997_Sep_CC_HT_2050\1997_Sep_CC_HT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1997_Sep_CC_LT_2050\1997_Sep_CC_LT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1997_Sep_CC_Org_2050\1997_Sep_CC_Org_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1998_Base_HT_New\1998_Base_HT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1998_Base_Org_New\1998_Base_Org_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1998_CC_HT_2050\1998_CC_HT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\1998_CC_Org_2050\1998_CC_Org_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\2007_CC_HT_2050\2007_CC_HT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\2007_CC_LT_2050\2007_CC_LT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\2007_CC_Org_2050\2007_CC_Org_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\2009_Base._LT_New\2009_Base._LT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\2009_Base_HT_New\2009_Base_HT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\2009_Base_Org_New\2009_Base_Org_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\2009_CC_HT_2050\2009_CC_HT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\2009_CC_LT_2050\2009_CC_LT_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\2009_CC_Org_2050\2009_CC_Org_2050.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\Sidr_Base_2007_HT_New\Sidr_Base_2007_HT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\Sidr_Base_LT_New\Sidr_Base_LT_New.dxfm" -x
start /w MzLaunch.exe "G:\MJI\SKZ\Script\Extracting Profile Series From DFSU File\Original_Script\dxfm\Sidr_Base_Org_New\Sidr_Base_Org_New.dxfm" -x
